[package]
name = "persistence"
version.workspace = true
edition.workspace = true

[dependencies]
command = { path = "../command" }
store = { path = "../store" }
bytes = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
