[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }

[[bin]]
name = "mini-redis"
path = "src/bin/mini-redis.rs"
