[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
protocol = { path = "../protocol" }
command = { path = "../command" }
store = { path = "../store" }
persistence = { path = "../persistence" }
replication = { path = "../replication" }
tokio = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }

[[bin]]
name = "mini-redis"
path = "src/bin/mini-redis.rs"
